# Amazon RDS On-demand MySQL instance pricing for the US-East region
# From http://aws.amazon.com/rds/pricing/
---
# Standard Deployment
standard:
  # DB Instance Class (On-Demand)
  db.t1.micro:      2.5
  db.m1.small:     10.5
  db.m1.large:     41.5
  db.m1.xlarge:    83.0
  # High-Memory DB Instance Class
  db.m2.xlarge:    58.5
  db.m2.2xlarge:   117.0
  db.m2.4xlarge:   234.0

# Multi-AZ Deployment
multi_az:
  # DB Instance Class (On-Demand)
  db.t1.micro:      5.0
  db.m1.small:     21.0
  db.m1.large:     83.0
  db.m1.xlarge:    166.0
  # High-Memory DB Instance Class
  db.m2.xlarge:    117.0
  db.m2.2xlarge:   234.0
  db.m2.4xlarge:   468.0
