# Amazon EC2 On-demand instance pricing for the US-East region
# From http://aws.amazon.com/ec2/pricing/
---
unix:
  # Standard On-Demand Instances
  m1.small:     8.5
  m1.large:     34.0
  m1.xlarge:    68.0
  # Micro On-Demand Instances
  t1.micro:     2.0
  # Hi-Memory On-Demand Instances
  m2.xlarge:    50.0
  m2.2xlarge:   100.0
  m2.4xlarge:   200.0
  # Hi-CPU On-Demand Instances
  c1.medium:    17.0
  c1.xlarge:    68.0
  # Cluster Compute Instances
  cc1.4xlarge:  130.0
  cc1.8xlarge:  240.0
  # Cluster GPU Instances
  cg1.4xlarge:  210.0

windows:
  # Standard On-Demand Instances
  m1.small:     12.0
  m1.large:     48.0
  m1.xlarge:    96.0
  # Micro On-Demand Instances
  t1.micro:     3.0
  # Hi-Memory On-Demand Instances
  m2.xlarge:    62.0
  m2.2xlarge:   124.0
  m2.4xlarge:   248.0
  # Hi-CPU On-Demand Instances
  c1.medium:    29.0
  c1.xlarge:    116.0
  # Cluster Compute Instances
  cc1.4xlarge:  161.0
  cc1.8xlarge:  297.0
  # Cluster GPU Instances
  cg1.4xlarge:  260.0
