# Amazon EC2 On-demand instance pricing for the US-East region
# From http://aws.amazon.com/ec2/pricing/
---
unix:
  # Standard On-Demand Instances
  m1.small:     8.5
  m1.medium:    16.0
  m1.large:     32.0
  m1.xlarge:    64.0
  # Micro On-Demand Instances
  t1.micro:     2.0
  # Hi-Memory On-Demand Instances
  m2.xlarge:    45.0
  m2.2xlarge:   90.0
  m2.4xlarge:   180.0
  # Hi-CPU On-Demand Instances
  c1.medium:    16.5
  c1.xlarge:    66.0
  # Cluster Compute Instances
  cc1.4xlarge:  130.0
  cc1.8xlarge:  240.0
  # Cluster GPU Instances
  cg1.4xlarge:  210.0

windows:
  # Standard On-Demand Instances
  m1.small:     11.5
  m1.medium:    23.0
  m1.large:     46.0
  m1.xlarge:    92.0
  # Micro On-Demand Instances
  t1.micro:     2.0
  # Hi-Memory On-Demand Instances
  m2.xlarge:    57.0
  m2.2xlarge:   114.0
  m2.4xlarge:   228.0
  # Hi-CPU On-Demand Instances
  c1.medium:    28.5
  c1.xlarge:    114.0
  # Cluster Compute Instances
  cc1.4xlarge:  161.0
  cc1.8xlarge:  297.0
  # Cluster GPU Instances
  cg1.4xlarge:  260.0
