#adapter: mysql2
#database: cloud_cost_tracker
username: root
pool: 10             # Best to use at lease one connection per tracked account
timeout: 10000       # Leave this nice and long
adapter: sqlite3
database: db/cloud_cost_tracker.sqlite3
